/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdraw;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DrawTest {
    @Test void appHasAGreeting() {
        assertTrue(true);
    }
}
